<?php

declare(strict_types=1);

session_start();

// Security/cache headers (avoid caching authenticated pages)
if (!headers_sent()) {
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    header('Pragma: no-cache');
    header('X-Content-Type-Options: nosniff');
    header('X-Frame-Options: DENY');
}

// Check if user is logged in
if (!isset($_SESSION['email'])) {
    header("Location: ../auth/login.php");
    exit();
}

$name = isset($_SESSION['name']) ? (string)$_SESSION['name'] : 'User';
$email = (string)($_SESSION['email'] ?? '');
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard - SecuredLogin</title>
    <link rel="stylesheet" href="../assets/css/dashboard.css">
</head>

<body>
    <div class="dashboard-container">
        <div class="dashboard-header">
            <h1>Welcome, <?php echo htmlspecialchars($name, ENT_QUOTES, 'UTF-8'); ?>!</h1>
            <p>You have successfully logged into your secure account.</p>
        </div>

        <div class="dashboard-content">
            <h2>Account Information</h2>
            <p><strong>Email:</strong> <?php echo htmlspecialchars($email, ENT_QUOTES, 'UTF-8'); ?></p>
            <p><strong>Name:</strong> <?php echo htmlspecialchars($name, ENT_QUOTES, 'UTF-8'); ?></p>
            <p><strong>Login Time:</strong> <?php echo date('Y-m-d H:i:s'); ?></p>

            <div class="math-practice-section">
                <h3>Math Practice</h3>
                <p>Test your math skills with our enhanced captcha system!</p>
                <div class="math-practice-info">
                    <h4>Available Operations:</h4>
                    <ul>
                        <li>➕ Addition (+)</li>
                        <li>➖ Subtraction (-)</li>
                        <li>✖️ Multiplication (×)</li>
                        <li>➗ Division (÷)</li>
                        <li>📊 Modulo (%)</li>
                        <li>🔢 Power (^)</li>
                        <li>√ Square Root (√)</li>
                    </ul>
                </div>
                <button id="practice-math-btn" class="practice-btn">Try Math Practice</button>
            </div>

            <a href="../includes/logout.php" class="logout-btn">Logout</a>
        </div>

        <!-- Math Practice Modal -->
        <div id="math-practice-modal" class="modal">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Math Practice</h2>
                    <span class="close">&times;</span>
                </div>
                <div class="modal-body">
                    <p>Solve this math problem:</p>
                    <div class="math-question">
                        <span id="practice-math-question"></span>
                    </div>
                    <div class="math-options-container" id="practice-math-options">
                        <!-- Options will be generated by JavaScript -->
                    </div>
                    <div class="practice-stats">
                        <p>Score: <span id="practice-score">0</span> / <span id="practice-total">0</span></p>
                    </div>
                    <div class="modal-buttons">
                        <button type="button" id="practice-verify">Verify</button>
                        <button type="button" id="practice-next">Next Question</button>
                        <button type="button" id="practice-reset">Reset Score</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="../assets/js/dashboard.js" defer></script>
</body>

</html>