<?php

declare(strict_types=1);

// Security/cache headers for auth pages
if (!headers_sent()) {
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    header('Pragma: no-cache');
    header('X-Content-Type-Options: nosniff');
    header('X-Frame-Options: DENY');
    header('Referrer-Policy: no-referrer');
}

session_start();

if (isset($_SESSION['email'])) {
    header("Location: ../dashboard/index.php");
    exit();
}
if (isset($_GET['show']) && $_GET['show'] === 'login') {
    header("Location: login.php");
    exit();
}
?>
<?php include '../includes/error_login.php'; ?>
<?php include '../includes/math_questions.php'; ?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Login - SecuredLogin</title>
    <link rel="stylesheet" href="../assets/css/style.css?v=<?php echo rawurlencode((string)time()); ?>" />
    <link rel="icon" href="../assets/images/lock.png">
    <script type="text/javascript" src="../assets/js/validation.js" defer></script>
</head>

<body>
    <div class="container-flex">
        <div class="wrapper">
            <h1>Login</h1>
            <p id="error-message" class="<?php echo $error_message ? 'error' : ''; ?>"><?php echo htmlspecialchars($error_message, ENT_QUOTES, 'UTF-8'); ?></p>
            <?php if ($success_message): ?>
                <p id="success-message" class="success"><?php echo htmlspecialchars($success_message, ENT_QUOTES, 'UTF-8'); ?></p>
            <?php endif; ?>
            <form id="form" action="../includes/auth_handler.php" method="POST">
                <div>
                    <label for="email-input">
                        <span>@</span>
                    </label>
                    <input
                        type="email"
                        name="email"
                        id="email-input"
                        placeholder="Email" autocomplete="username" />
                </div>
                <div>
                    <label for="password-input">
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            height="24"
                            viewBox="0 -960 960 960"
                            width="24">
                            <path
                                d="M240-80q-33 0-56.5-23.5T160-160v-400q0-33 23.5-56.5T240-640h40v-80q0-83 58.5-141.5T480-920q83 0 141.5 58.5T680-720v80h40q33 0 56.5 23.5T800-560v400q0 33-23.5 56.5T720-80H240Zm240-200q33 0 56.5-23.5T560-360q0-33-23.5-56.5T480-440q-33 0-56.5 23.5T400-360q0 33 23.5 56.5T480-280ZM360-640h240v-80q0-50-35-85t-85-35q-50 0-85 35t-35 85v80Z" />
                        </svg>
                    </label>
                    <div class="password-container">
                        <input
                            type="password"
                            name="password"
                            id="password-input"
                            placeholder="Password" autocomplete="current-password" />
                        <img src="/SecuredLogin/assets/icons/eye-close1.png" id="toggle-password-visibility" alt="Toggle Password Visibility">
                    </div>
                </div>
                <div class="checkbox-container">
                    <input type="checkbox" id="show-math-modal" name="show-math-modal">
                    <label for="show-math-modal">Click the Checkbox to Login your Account</label>
                </div>
                <input type="hidden" name="math-answer" id="math-answer-hidden" value="">
                <button type="submit" name="login" id="login-btn" disabled>Login</button>
            </form>
            <p>New here? <a href="signup.php">Create an Account</a></p>
        </div>
    </div>

    <!-- Math Modal -->
    <div id="math-modal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Math Verification</h2>
                <span class="close">&times;</span>
            </div>
            <div class="modal-body">
                <p>Please solve this math problem to verify your Account</p>
                <div class="math-question">
                    <span id="math-question" data-question="<?php echo htmlspecialchars($question, ENT_QUOTES, 'UTF-8'); ?>" data-answer="<?php echo htmlspecialchars((string)$answer, ENT_QUOTES, 'UTF-8'); ?>"><?php echo htmlspecialchars($question, ENT_QUOTES, 'UTF-8'); ?></span>
                </div>
                <div class="math-options-container" id="math-options">
                    <!-- Options will be generated by JavaScript -->
                </div>
                <input type="hidden" name="math-answer" id="math-answer" value="">
                <div class="loader" id="math-loader"></div>
                <div class="modal-buttons">
                    <button type="button" id="verify-math">Verify</button>
                    <button type="button" id="reset-math">Reset</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Confirmation Modal -->
    <div id="confirmation-modal" class="confirmation-modal">
        <div class="confirmation-content">
            <h3>Reset Math Question</h3>
            <p>Are you sure you want to reset the math question? This will generate a new question.</p>
            <div class="confirmation-buttons">
                <button type="button" id="confirm-reset">Yes, Reset</button>
                <button type="button" id="cancel-reset">Cancel</button>
            </div>
        </div>
    </div>

    <!-- Success Modal -->
    <div id="success-modal" class="success-modal">
        <div class="success-content">
            <div class="success-icon">
                <img src="../assets/images/4240-verified-green-animated.gif" alt="Verification Successful" style="width: 80px; height: 80px;">
            </div>
            <h3>Verification Successful!</h3>
            <p>Math verification completed successfully. You can now proceed with your login.</p>
            <div class="success-buttons">
                <button type="button" id="continue-login">Continue</button>
            </div>
        </div>
    </div>

    <script src="../assets/js/login.js" defer></script>
</body>

</html>